### ISSUE TITLE
Issue for google drive link for your dataset

### ISSUE THREAD

**Issue by mshowbi1** [xiaofeng94/RefineDNet-for-dehazing#1]
Hi, I am a student at Yonsei Univ. South Korea.

It is hard to reach your BAIDU cloud, and I found that you have in mind to open the google drive link for your dataset.

Can you forward your dataset RESIDE-unpaired and refined_DCP_outdoor in google drive? 

Thank you.

**Comment by xiaofeng94** [comment]
Hello @mshowbi1 , 

I have updated the link. Please check it.

Best.

**Comment by mshowbi1** [comment]
Thank you for your help.

Sincerely

2021년 4월 15일 (목) 오후 1:26, shiyu ***@***.***>님이 작성:
