### ISSUE TITLE
training using GPU

### ISSUE THREAD

**Issue by wangjing835** [xiaofeng94/RefineDNet-for-dehazing#2]
Hello，thanks for your work and l'm sorry to bother you. When I use your code for training, I found it ran on cpu instead of gpu. How can I train it on gpu？Where should I modify？

**Comment by xiaofeng94** [comment]
Hi,

The training script should run on GPU. Please make sure torch.cuda.is_available() == True, and pass the parameter -- gpu_ids 0 (which should be the default setting) to train.py.

**Comment by wangjing835** [comment]
> Hi,
> 
> The training script should run on GPU. Please make sure torch.cuda.is_available() == True, and pass the parameter -- gpu_ids 0 (which should be the default setting) to train.py.

I tried this but failed. 
Then I change `N = self.boxfilter( torch.ones(p.size()) )` in `network.py` to
```
if I.is_cuda:
            N = self.boxfilter( torch.ones(p.size()).cuda())
        else:
            N = self.boxfilter( torch.ones(p.size()))
```
it works. thanks for your code!
