### ISSUE TITLE
about “dark channel for single image dehaze”

### ISSUE THREAD

**Issue by JunkaiFan** [xiaofeng94/RefineDNet-for-dehazing#3]
Judging from the results displayed by visdom, your DCP solution seems to be problematic
![dcp_J_vis](https://user-images.githubusercontent.com/58910346/126887484-987b6e70-883a-40c1-ad9a-e1430e32dd67.jpg)

**Comment by xiaofeng94** [comment]
Hi,

Would you like to provide more descriptions? 
DCP with poor parameters can lead to this result.

**Comment by JunkaiFan** [comment]
> Hi,
> 
> Would you like to provide more descriptions?
> DCP with poor parameters can lead to this result.

I directly show that the result of dcp_J_vis in your code is on visdom. 
In fact, the effect of DCP should not be so bad, so I have some doubts

**Comment by xiaofeng94** [comment]
Hi,

DCP may fail in some cases. You may refer to Fig.19 of the TPAMI version paper.
Also, DCP depends on manually tuned parameters, and poor parameters result in poor results.

**Comment by JunkaiFan** [comment]
Okay, thank you very much for your answers

**Comment by JunkaiFan** [comment]
> Hi,
> 
> DCP may fail in some cases. You may refer to Fig.19 of the TPAMI version paper.
> Also, DCP depends on manually tuned parameters, and poor parameters result in poor results.

Okay, thank you very much for your answers
