### ISSUE TITLE
The details of the datasets

### ISSUE THREAD

**Issue by LPengYang** [xiaofeng94/RefineDNet-for-dehazing#7]
Hi, 我们注意到关于室外数据部分文章中提到RESIDE数据中提供里8970张清晰图像和9129张雾霾图像,由于质量问题对其进行了手工筛选，最后得到3577张清晰图片和2903张雾霾图片（RESIDE-unpaired）。但是根据RESIDE数据的构成其室外图片主要来源有：SOTS(outdoor)： 500 张清晰图片和对应的合成雾霾图片； OTS：2061张清晰图片对应72135张合成雾霾图片；HSTS：10张真实的雾霾图片以及10张真实的雾霾图片(带对应合成雾霾图片)；URHI：4809张无标注的真实雾霾图片；RTTS：4322张有标注的真实雾霾图片。请问文章中提到的8970张清晰图片和9129张雾霾图片的来源具体是什么样呢。另外我们注意到提供的RESIDE-unpaired的雾霾图片部分有来自SOTS(outdoor)的ground-truth图片(比如第一张)，这些图片在SOTS中是作为真实清晰图片对待的(虽然这些图片确实带有严重的雾霾残留)，因此我们想了解更多关于RESIDE-unpaired的细节以便之后的使用。

**Comment by xiaofeng94** [comment]
Hey @YangPY-0,
 
RESIDE-unpaired 中没有合成的雾霾图片，我们仅使用了其提供的真实图像。
所有图像均来自与RESIDE数据集，可从其官网 (https://sites.google.com/view/reside-dehaze-datasets/reside-v0) 获取
