### ISSUE TITLE
How to evaluate the best model after training ?

### ISSUE THREAD

**Issue by CharlesLayn** [xiaofeng94/RefineDNet-for-dehazing#8]
Hello, thanks for your excellent work! I wonder how you can tell which model can achieve the best dehazing effect? Because it seems that the results cannot be observed from the loss printed during the training process, and after training, sometimes the model of 60th epoch works better than the 90th in some index like VI/RI/VSI, and there may be some models works better than the 60th, but it seems a little hard to judge. My current practice is to use each model to dehaze the images in test set, and then use MATLAB to measure the dehazed images. I don't know if this is correct, so I want to ask how you judge which epoch is the best model ?

**Comment by xiaofeng94** [comment]
Hey, you may also construct a small set of validation images and evaluate SSIM/PSNR on them for every N iterations. SSIM/PSNR may not be the best metric but somehow indicate your results.
